//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSignWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public int CardNo { get; set; }
        public string Name { get; set; }
        public string OutID { get; set; }
        public int CardSN { get; set; }
        public bool Sex { get; set; }
        public string DeptCode { get; set; }
        public string Pwd { get; set; }
        public System.DateTime MakeCardDT { get; set; }
        public int MagID { get; set; }
        public int Status { get; set; }
        public string IDCardNo { get; set; }
        public bool IfCard { get; set; }
        public bool IfNeedKQ { get; set; }
        public int Ver { get; set; }
        public string SCardSNR { get; set; }
        public Nullable<System.DateTime> DisabledTime { get; set; }
        public int SN { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> CardSfId { get; set; }
        public Nullable<int> CustSource { get; set; }
        public int IfPhoto { get; set; }
        public string CellphoneNo { get; set; }
        public string PCellPhoneNo { get; set; }
    }
}
