//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSignWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int ID { get; set; }
        public Nullable<int> WD_EmpNo { get; set; }
        public string CName { get; set; }
        public string EName { get; set; }
        public string Legal_EntityFinal { get; set; }
        public string emp_status { get; set; }
        public Nullable<int> siteid { get; set; }
        public string SiteName { get; set; }
        public string SiteCode { get; set; }
        public string DLFlag { get; set; }
        public string AD_AccountFinal { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public Nullable<System.DateTime> Leave_Date { get; set; }
        public string Cost_Center_ID { get; set; }
        public string Cost_Center { get; set; }
        public string Business_Group { get; set; }
        public string Dept_Name { get; set; }
        public string Manager_Name { get; set; }
        public Nullable<int> Manager_ID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Extension { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
