//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSignWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_training()
        {
            this.tbl_trainee = new HashSet<tbl_trainee>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid ref_course_id { get; set; }
        public string trainer_organizer { get; set; }
        public string organizer { get; set; }
        public string venue { get; set; }
        public Nullable<int> plan_reach { get; set; }
        public Nullable<int> actual_reach { get; set; }
        public Nullable<double> total_training_time { get; set; }
        public Nullable<int> pass { get; set; }
        public Nullable<System.DateTime> plan_start_time { get; set; }
        public Nullable<System.DateTime> plan_end_time { get; set; }
        public Nullable<System.DateTime> actual_end_time { get; set; }
        public string end_lector_workid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trainee> tbl_trainee { get; set; }
    }
}
