//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSignWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_course
    {
        public System.Guid id { get; set; }
        public string course_no { get; set; }
        public string course_context { get; set; }
        public Nullable<double> course_time { get; set; }
    }
}
