//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSignWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_lector()
        {
            this.tbl_lector_course_link = new HashSet<tbl_lector_course_link>();
            this.tbl_training_lector_link = new HashSet<tbl_training_lector_link>();
        }
    
        public System.Guid id { get; set; }
        public string lector_workid { get; set; }
        public string lector_en_name { get; set; }
        public string lector_cn_name { get; set; }
        public string memo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lector_course_link> tbl_lector_course_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_training_lector_link> tbl_training_lector_link { get; set; }
    }
}
