//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSignWeb.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingSign_Entities : DbContext
    {
        public TrainingSign_Entities()
            : base("name=TrainingSign_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<tbl_course> tbl_course { get; set; }
        public virtual DbSet<tbl_delete_trainee_log> tbl_delete_trainee_log { get; set; }
        public virtual DbSet<tbl_lector> tbl_lector { get; set; }
        public virtual DbSet<tbl_lector_course_link> tbl_lector_course_link { get; set; }
        public virtual DbSet<tbl_trainee> tbl_trainee { get; set; }
        public virtual DbSet<tbl_training> tbl_training { get; set; }
        public virtual DbSet<tbl_training_lector_link> tbl_training_lector_link { get; set; }
    }
}
